import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
  return (
    <div className="content">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HeaderIcon.ico" />
      </Head>
      <Navbar />
      {children}
      {/* <footer>
        <span>Created By Hayden West</span>
      </footer> */}
    </div>
  );
};

export default Layout;
