import Head from "next/head";

const Navbar = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HeaderIcon.ico" />
      </Head>
      <nav>
        <div className="logo">
          <h1>Header Bar</h1>
        </div>
        <a>Home</a>
        <a>About</a>
        <a>Other</a>
      </nav>
    </>
  );
};

export default Navbar;
